title = 'マイナスから始めるC言語'
baseURL = 'https://clang-lecture.watasuke.tk'
languageCode = 'ja-jp'
theme = "relearn"

[outputs]
home = ["HTML", "RSS", "JSON"]

# theme
[params]
themeVariant = [ "dark", "relearn-light" ]

[markup]
  [markup.highlight]
    guessSyntax = false
    style = "monokai"
